# Generated by Django 5.1.4 on 2025-07-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=500)),
                ('last_donate_date', models.DateField()),
                ('any_disease', models.CharField(blank=True, max_length=100)),
                ('allergies', models.CharField(blank=True, max_length=100)),
                ('heart_condition', models.CharField(blank=True, max_length=100)),
                ('bleeding_disorder', models.CharField(blank=True, max_length=100)),
                ('hiv_hcv', models.CharField(blank=True, max_length=50)),
                ('aadhar_card', models.ImageField(blank=True, null=True, upload_to='donor_aadhar/')),
            ],
        ),
    ]
