# Generated by Django 5.1.4 on 2025-07-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorregistration',
            old_name='date',
            new_name='Birth_date',
        ),
    ]
