# Generated by Django 5.1.4 on 2025-07-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_date_donorregistration_birth_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donorregistration',
            table='donorList',
        ),
    ]
