# Generated by Django 5.1.4 on 2025-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_donorregistration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregistration',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='donorregistration',
            name='username',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='Birth_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='aadhar_card',
            field=models.ImageField(blank=True, default='', null=True, upload_to='donor_aadhar/'),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='any_disease',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='bleeding_disorder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='blood_group',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='email',
            field=models.EmailField(default='', max_length=123),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='heart_condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='hiv_hcv',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='home_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='last_donate_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
