# Generated by Django 5.1.4 on 2025-07-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_donorregistration_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorregistration',
            old_name='Birth_date',
            new_name='birth_date',
        ),
    ]
