# Generated by Django 5.1.4 on 2025-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_birth_date_donorregistration_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregistration',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='donor_aadhar/'),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='allergies',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='any_disease',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='bleeding_disorder',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='email',
            field=models.EmailField(max_length=123),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='heart_condition',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='hiv_hcv',
            field=models.CharField(blank=True, default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='home_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='last_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
